baseURL = "https://yannickschutz.com/"
languageCode = "en-us"
title = "ğŸ¤·ğŸ¼â€â™‚ï¸ Yannick Schutz"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  footer = 'ğŸŒ² Please consider the environment before printing this website'

[params.social]
  email = "hello@yannickschutz.com"

[params.fathom]
  host = "logs.vadrouilles.co"
  siteID = "IMJQP"

[permalinks]
  posts = "/:slug"
